/**
 * Must match the numeric literal `maxDuration` in `src/app/api/process-pdf/route.ts`.
 * **300** = Vercel Pro (long PDF + AI runs). On **Hobby**, change both files to **60**.
 */
export const PDF_PROCESS_MAX_DURATION_SEC = 300;

/**
 * Anthropic client timeout for course-build calls.
 *
 * This used to be `maxDuration - 40s` — 260 s of a 300 s invocation — which
 * left no room to retry, persist progress, or return cleanly. One hung call
 * consumed the whole budget and the lambda was killed with completed-but-
 * unsaved modules still in memory: paid for, discarded, then regenerated by
 * the client's next poll.
 *
 * Half the invocation budget lets a stuck call fail early enough for the batch
 * to save what it has and hand the job on to the next invocation.
 */
export function getPdfAnthropicTimeoutMs(): number {
  return Math.max(45_000, Math.round(PDF_PROCESS_MAX_DURATION_SEC * 1000 * 0.5));
}
