/** Curated names for onboarding autocomplete (not exhaustive). */
export const SCHOOL_NAME_SUGGESTIONS: readonly string[] = [
  "Harvard University",
  "Stanford University",
  "Massachusetts Institute of Technology",
  "Yale University",
  "Princeton University",
  "Columbia University",
  "University of Chicago",
  "University of Pennsylvania",
  "California Institute of Technology",
  "Duke University",
  "Northwestern University",
  "Johns Hopkins University",
  "Cornell University",
  "University of California, Berkeley",
  "University of California, Los Angeles",
  "University of Michigan",
  "University of Virginia",
  "Carnegie Mellon University",
  "University of North Carolina at Chapel Hill",
  "University of Southern California",
  "New York University",
  "University of Texas at Austin",
  "University of Washington",
  "University of Wisconsin–Madison",
  "University of Illinois Urbana-Champaign",
  "Georgia Institute of Technology",
  "University of Florida",
  "Ohio State University",
  "Pennsylvania State University",
  "Purdue University",
  "University of Maryland",
  "University of Minnesota",
  "Texas A&M University",
  "Rutgers University",
  "University of California, San Diego",
  "University of California, Davis",
  "Boston University",
  "University of Pittsburgh",
  "University of Colorado Boulder",
  "University of Arizona",
  "Arizona State University",
  "University of Utah",
  "Indiana University Bloomington",
  "Michigan State University",
  "University of Iowa",
  "University of Oregon",
  "University of Connecticut",
  "University of Massachusetts Amherst",
  "North Carolina State University",
  "Virginia Tech",
  "University of Georgia",
  "Florida State University",
  "University of South Florida",
  "San Diego State University",
  "San Francisco State University",
  "California State University, Long Beach",
  "California State University, Fullerton",
  "California Polytechnic State University",
  "University of California, Irvine",
  "University of California, Santa Barbara",
  "University of California, Riverside",
  "University of Houston",
  "University of Central Florida",
  "University of Kentucky",
  "Louisiana State University",
  "University of Tennessee",
  "University of Alabama",
  "University of Oklahoma",
  "University of Kansas",
  "Iowa State University",
  "University of Nebraska–Lincoln",
  "University of Missouri",
  "University of Arkansas",
  "University of Mississippi",
  "University of Nevada, Las Vegas",
  "University of Hawaii at Mānoa",
  "University of Alaska Fairbanks",
  "McGill University",
  "University of Toronto",
  "University of British Columbia",
  "University of Waterloo",
  "University of Alberta",
  "Queen’s University",
  "Western University",
  "University of Oxford",
  "University of Cambridge",
  "Imperial College London",
  "University College London",
  "London School of Economics",
  "King’s College London",
  "University of Edinburgh",
  "University of Manchester",
  "ETH Zurich",
  "University of Zurich",
  "National University of Singapore",
  "University of Hong Kong",
  "University of Melbourne",
  "University of Sydney",
  "Australian National University",
  "High school (other)",
];

export function filterSchoolSuggestions(
  query: string,
  limit = 12
): string[] {
  const q = query.trim().toLowerCase();
  if (q.length < 1) return [...SCHOOL_NAME_SUGGESTIONS].slice(0, limit);
  const scored = SCHOOL_NAME_SUGGESTIONS.filter((s) =>
    s.toLowerCase().includes(q)
  );
  return scored.slice(0, limit);
}
